name: CI
on:
  push:
    branches: [bisect]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        go: ['1.20.x', '1.21.x', '1.22.x', '1.23.x', '1.24.x']
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - run: rustup target add x86_64-pc-windows-gnu
    - run: cmake -S crates/c-api -B target/c-api --install-prefix "$(pwd)/artifacts" -DWASMTIME_TARGET=x86_64-pc-windows-gnu
      shell: bash
      working-directory: wasmtime

    - run: cmake --build target/c-api
      working-directory: wasmtime

    - run: cmake --install target/c-api
      working-directory: wasmtime
    - run: rm -rf build/include && cp -r wasmtime/artifacts/include build
      shell: bash
    - run: cp wasmtime/artifacts/lib/libwasmtime.a build/windows-x86_64/
      shell: bash

    # then run our go tests ...
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: go test
