name: CI
on:
  push:
    branches: [bisect]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        go: ['1.20.x', '1.21.x', '1.22.x', '1.23.x', '1.24.x']
    steps:
    - uses: actions/checkout@v4

    # then run our go tests ...
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: go test
